name: CubicCountdown
version: 1.2.2_BETA
main: de.timecoding.cc.CubicCountdown
api-version: 1.13
softdepend: [ PlaceholderAPI ]
description: "A plugin which is able to start a countdown when a cube is full/empty (of blocks)"

commands:
  cubiccountdown:
    aliases:
      - cc
    description: "A command which allows players to do the CubicCountdown setup"
